theme: minima
title: leakyfaucets
author: Frank Zhang
description: This is my personal website for posting blogs.
github_username: leakyfaucets
minima:
  date_format: "%Y-%m-%d"
  show_excerpts: true
