remote_theme: "jekyll/minima@4de3223"
title: leakyfaucets
author:
  name: Frank Zhang
description: >
  leakyfaucets is a website about programming, statistics, and other topics of interest to the author. 
  It serves as a platform for sharing knowledge, insights, and experiences.
minima:
  skin: auto
  nav_pages:
    - about.md
    - categories.md
  date_format: "%Y-%m-%d"
  show_excerpts: true
  social_links:
    - title: GitHub profile
      icon: github
      url: "https://github.com/leakyfaucets"
  hide_site_feed_link: true
